language: cpp
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
cache: ccache
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libx11-dev
    - linux-headers-$(uname -r)
install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- git clone --depth 1 https://chromium.googlesource.com/libyuv/libyuv && cd libyuv
  && make -f linux.mk libyuv.a && sudo cp libyuv.a /usr/lib
  && cd include && sudo cp -r * /usr/include && cd ../..
- cd /tmp && wget https://www.1stvision.com/cameras/IDS/sw/uEye-Linux-4.90.06-64.tgz && tar xvzf uEye-Linux-4.90.06-64.tgz && sudo ./ueyesdk-setup-4.90.06-usb-amd64.gz.run --nox11
- cd && chalmers-revere/opendlv-device-camera-ueye && mkdir -p build && cd build && cmake .. && make
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: OGZKtAzjWDLQmEC66fdY27psNIEig992SJD4ASXV8F9NJ75FndJo+QdDEQgEqmm499wffCJxD7wMSWrDsYWgv+hQonCwPkfepdHgm4EokVYBcdy1ib5GLjEdH8YJId6r/a6zAcr+b/4sjwJ00iUD0UKzzhGaEc9QO1A8K/u8ltiqhsSZQHvDJ+4eO54U82A4S7FXMTXHaJJm6SK+08UACJMXHnwfRYR5rx3GwEBkzGAYKi3XPDiWYdaSNEcGdVVyp4nC8yHx6L97IgMKx24qqGmvbm8mw6OtY4UglejqIxBlnGHcmFWbF0abADoHOYicbUEG8HNledk8bce08hkJAtP2ijbXA9J7J7G+3KvoEKhIsfBteNZeBXdoYfBxEQLXFMQcQcKo9WcM9FpI64FGOBK05ZIMQo7tFk8uAPDvwezGxD/euF/lhEd7fFY5lyb6E1tWmQKBGI2hQmT6U+uguhrXNNTGm5kcwmsOYhhszWdOmIsVTvDS2UY7wJPAvCVDyRDGdB2s3KkBCNU0t3f+k+R1ip0BdgqEV6dCR6NVZyL2tPEgSoY8/bE9yn9FfzHPU7cKNnwxaRGdkbK14d6Yu5XsPOboThITNblWJS5zpNSoJhnI/Mr87AIKTMVER3eN9hZtyfyMAySwLQGdQE5MlYUNo2YaITDFhmFrsAEY+OU=
